### ISSUE TITLE
Nothing is generated

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [Dr-Emann/java-haxe-extern-creator#4]
I run java-haxe-extern-creator with these arguments:

```
-source /home/ls/tmp -output -/home/ls/tmp/output -packages com.nuggeta.gameserver.model
```

where /home/ls/tmp/com/nuggeta/gameserver/model contains *.class files.
But nothing is generated in the output directory ...

**Comment by Dr-Emann** [comment]
The default branch is the `doclet` branch, which works with .java source code files, not .class files. You can try the master branch, if you need support for class files. However, with recent versions of haxe, you should be able to use `-java-lib 'folder/containing/class/files'` in your .hxml, so this project is largely unmaintained. If you have a reason to use this generator over the -java-lib method, I'd be happy to try to fix any issues you find in the master branch, though.
